---
# Source: vehicle-trip-analyzer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-trip-analyzer
  labels:
    app: vehicle-trip-analyzer
    chart: vehicle-trip-analyzer-1.0.0
    release: vehicle-trip-analyzer
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle-trip-analyzer
      release: vehicle-trip-analyzer
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
    
  template:
    metadata:
      labels:
        app: vehicle-trip-analyzer
        release: vehicle-trip-analyzer
      annotations:
        app: vehicle-trip-analyzer
        
    spec:
      containers:
        - name: vehicle-trip-analyzer
          image: cyberjohn00/vehicle-trip-analyzer:1.0.0
          imagePullPolicy: Always
          env:
          - name: APIKEY
            value: "xxx"
          - name: FLASK_APP
            value: "/app/main.py"
          - name: FLASK_ENV
            value: "development"
          - name: PASSWORD
            value: "xxx"
          - name: USERNAME
            value: "foo"
          ports:
          - containerPort: 80
            protocol: TCP
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
            
          resources:
            limits:
              cpu: 400m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 200Mi
            
      restartPolicy: Always

