{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "vehicle-trip-analyzer.fullname" . }}"
  labels:
    app: {{ template "vehicle-trip-analyzer.name" . }}
    chart: {{ template "vehicle-trip-analyzer.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- if .Values.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- if .Values.ingress.hostName }}
  - host: {{ .Values.ingress.hostName }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "vehicle-trip-analyzer.fullname" . }}
            servicePort: {{ .Values.ingress.port }}
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- if  .Values.ingress.hostName }}
    - {{ .Values.ingress.hostName }}
    secretName: {{  .Values.ingress.tlsSecret }}
    {{- else}}
    - secretName: {{  .Values.ingress.tlsSecret }}
    {{- end }}
{{- end }}
{{- end }}
