apiVersion: v1
kind: Service
metadata:
  name: {{ template "vehicle-trip-analyzer.fullname" . }}
  labels:
    app: {{ template "vehicle-trip-analyzer.name" . }}
    chart: {{ template "vehicle-trip-analyzer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ template "vehicle-trip-analyzer.name" . }}
    release: {{ .Release.Name }}
