pipeline {
    agent none
    environment {
        GIT_SSL_NO_VERIFY = 'true'
        PROJECT_NAME = 'vehicle-trip-analyzer'
        RELEASE = "$PROJECT_NAME"
        NAMESPACE = 'default'
        CLUSTER = 'nonprod'
        APP_VERSION = "1.0.$BUILD_NUMBER"
    }
    triggers { pollSCM('* * * * *') }
    stages {
        stage('checkout') {
            agent any
            steps {
                git 'https://github.com/EugeneLyapin/vehicle-trip-analyzer'
            }
        }
        stage('docker') {
            agent {
                kubernetes {
                label 'docker'
                yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:1.11
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
"""
                }
            }
            steps {
                container('docker') {
                    git 'https://github.com/EugeneLyapin/vehicle-trip-analyzer'
                    dir('docker') {
                        withCredentials([usernamePassword(credentialsId: 'dockerhub-cyberjohn00', usernameVariable: 'USERNAME', passwordVariable: 'CI_BUILD_TOKEN')]) {
                            sh "docker login -u $USERNAME -p $CI_BUILD_TOKEN docker.io"
                        }
                        sh "docker build -t cyberjohn00/vehicle-trip-analyzer:${APP_VERSION} ."
                        sh "docker push cyberjohn00/vehicle-trip-analyzer:${APP_VERSION}"
                    }
                }
            }
        }
        stage('rollout Project') {
            agent any
            steps {
                sh 'bash helm/jenkins/files/jobs/rolloutProject.sh'
            }
        }
    }
}
